FROM node:8.8
LABEL maintainer="Tyler Battle <tbattle@boundlessgeo.com>"

ENV DOCKER true
WORKDIR /opt/mapstory

RUN set -ex \
    && npm install -g \
        protractor \
    && npm link \
        protractor \
        selenium-webdriver \
    && npm install \
        pix-diff \
    && webdriver-manager update

WORKDIR /opt/mapstory/tests
COPY mapstory/tests ./

CMD ["./runE2ETests.sh"]
