#!/bin/sh
set -e

# setup 2 databases for mapstory
# mapstory for django and mapstory_data for geoserver
# this requires postgres and postgis to be installed

# to totally reset, the following can be run
# dropdb mapstory; dropdb mapstory_data; psql -c 'DROP USER mapstory'

createdb mapstory
createdb mapstory_data

psql -c "CREATE USER mapstory WITH PASSWORD 'mapstory'"
psql -c "GRANT ALL PRIVILEGES ON DATABASE mapstory to mapstory"
psql -d mapstory_data -c "create extension postgis"
psql -c "GRANT ALL PRIVILEGES ON DATABASE mapstory_data to mapstory"
