#!/bin/bash

ROOT="$(readlink -f $(dirname $0)/../..)"
RUNNER_JAR="${ROOT}/downloaded/jetty-runner-8.1.8.v20121106.jar"
RUNNER_XML="${ROOT}/scripts/misc/jetty-runner.xml"

JETTY_HOME=${JETTY_HOME:=${ROOT}/geoserver/}

# allow debugging via DEBUG env
DEBUG_OPTS=${DEBUG+"-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=4000,server=y,suspend=y"}

# default data directory or use provided via env
DATA_DIR=${DATA_DIR-"${ROOT}/geoserver/data"}
DATA_DIR=$(readlink -m $DATA_DIR)

# enable security client via DBSECURITY env
DBSECURITY_PASS=${DBSECURITY_PASS:=mapstory}
SECURITY_CLIENT=${DBSECURITY+"-Dorg.geonode.security.databaseSecurityClient.url=jdbc:postgresql://localhost:5432/mapstory?user=mapstory&password=${DBSECURITY_PASS}"}

# use importer bdb store
IMPORTER_OPTS=${IMPORTER_BDB+"-Dorg.geoserver.importer.store=bdb -Dorg.geoserver.importer.bdb.binding=serial"}

MAX_HEAP=${MAX_HEAP:=1024}
MAX_PERM=${MAX_PERM:=256}

cd $DATA_DIR
exec java $DEBUG_OPTS \
-Xmx${MAX_HEAP}M \
-Dcom.sun.management.jmxremote=true \
-Djava.awt.headless=true \
-XX:+UseG1GC \
-XX:MaxPermSize=${MAX_PERM}m \
-DGEOSERVER_DATA_DIR=$DATA_DIR \
-Dorg.eclipse.jetty.server.webapp.parentLoaderPriority=true \
$IMPORTER_OPTS \
$SECURITY_CLIENT \
-Djetty.home=${JETTY_HOME} \
-jar $RUNNER_JAR \
--port 8080 \
$RUNNER_XML


