# mapstory.org configuration
version: '3.7'
services:
  composer:
    build:
      args:
        - DEPLOYMENT=production

  pgadmin:
    ports:
      - "5050:5050"
    secrets:
      - env_db_auth

  elasticsearch:

  rabbitmq:
    secrets:
      - env_rabbitmq_auth

  django:
    env_file:
      - docker/env/staging/public_host.env
      - docker/env/staging/geoserver.env
      - docker/env/staging/mapstory.env
    secrets:
      - env_db_auth
      - env_email_auth
      - env_geoserver_auth
      - env_rabbitmq_auth
      - env_slack_auth
      - env_social_auth

  celery:
    env_file:
      - docker/env/staging/public_host.env
      - docker/env/staging/geoserver.env
      - docker/env/staging/mapstory.env
    secrets:
      - env_db_auth
      - env_email_auth
      - env_geoserver_auth
      - env_rabbitmq_auth
      - env_slack_auth
      - env_social_auth

  django_volumes:

  geoserver:
    env_file:
      - docker/env/staging/public_host.env
      - docker/env/staging/geoserver.env
    secrets:
      - env_db_auth
      - env_geoserver_auth

  nginx:
    env_file:
      - docker/env/staging/public_host.env
    environment:
      - NGINX_NUM_WORKERS=2
      - NGINX_FILE_CACHE_ENABLED=True
    secrets:
      - ssl_cert
      - ssl_key

volumes:
  geoserver:
    driver: rexray
  mapstory_media:
    driver: rexray

secrets:
  ssl_cert:
    file: ../secrets/ssl_cert
  ssl_key:
    file: ../secrets/ssl_key
  env_db_auth:
    file: ../secrets/env/db_auth
  env_email_auth:
    file: ../secrets/env/email_auth
  env_geoserver_auth:
    file: ../secrets/env/geoserver_auth
  env_rabbitmq_auth:
    file: ../secrets/env/rabbitmq_auth
  env_slack_auth:
    file: ../secrets/env/slack_auth
  env_social_auth:
    file: ../secrets/env/social_auth
