# storyscapes test configuration
version: '3.7'
services:
  composer:
    build:
      args:
        - DEPLOYMENT=production

  postgres:
    image: quay.io/mapstory/postgis:9.6.10-alpine
    env_file:
      - docker/env/storyscapes/postgres.env
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      internal:
    expose:
      - "5432"

  pgadmin:
    secrets:
      - env_db_auth

  elasticsearch:

  rabbitmq:
    secrets:
      - env_rabbitmq_auth

  django:
    env_file:
      - docker/env/storyscapes/public_host.env
      - docker/env/storyscapes/geoserver.env
      - docker/env/storyscapes/mapstory.env
    links:
      - postgres
    secrets:
      - env_db_auth
      - env_email_auth
      - env_geoserver_auth
      - env_rabbitmq_auth
      - env_slack_auth
      - env_social_auth

  celery:
    env_file:
      - docker/env/storyscapes/public_host.env
      - docker/env/storyscapes/geoserver.env
      - docker/env/storyscapes/mapstory.env
    secrets:
      - env_db_auth
      - env_email_auth
      - env_geoserver_auth
      - env_rabbitmq_auth
      - env_slack_auth
      - env_social_auth

  django_volumes:

  geoserver:
    env_file:
      - docker/env/storyscapes/public_host.env
      - docker/env/storyscapes/geoserver.env
    links:
      - postgres
    secrets:
      - env_db_auth
      - env_geoserver_auth

  nginx:
    env_file:
      - docker/env/storyscapes/public_host.env
    secrets:
      - ssl_cert
      - ssl_key

volumes:
  geoserver:
  mapstory_media:
  postgres:

secrets:
  ssl_cert:
    file: ../secrets/ssl_cert
  ssl_key:
    file: ../secrets/ssl_key
  env_db_auth:
    file: ../secrets/env/db_auth
  env_email_auth:
    file: ../secrets/env/email_auth
  env_geoserver_auth:
    file: ../secrets/env/geoserver_auth
  env_rabbitmq_auth:
    file: ../secrets/env/rabbitmq_auth
  env_slack_auth:
    file: ../secrets/env/slack_auth
  env_social_auth:
    file: ../secrets/env/social_auth
  postgres_user:
    file: ../secrets/postgres/postgres_user
  postgres_password:
    file: ../secrets/postgres/postgres_password
  postgres_db:
    file: ../secrets/postgres/postgres_db


