# configuration for running tests
# it assumes that the local 'override' config has been loaded
version: '3.1'
services:
  django:
    command: --init-db --test
    volumes:
      - ./cover:/srv/mapstory/cover

  celery:
    environment:
      CELERY_NUM_WORKERS: 1
