# Dev configuration
version: '3.1'
services:
  postgres:
    image: mdillon/postgis:9.5
    env_file:
      - docker/env/dev/db_auth.env
      - docker/env/dev/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - "5432"

  pgadmin:
    links:
      - postgres
    env_file:
      - docker/env/dev/db_auth.env

  elasticsearch:
    ports:
      - "9200:9200"

  rabbitmq:
    image: rabbitmq:3.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=mapstory
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=mapstory

  django:
    links:
      - postgres
    extra_hosts:
      - docker:nginx
    env_file:
      - docker/env/dev/public_host.env
      - docker/env/dev/geoserver.env
      - docker/env/dev/mapstory.env
      - docker/env/dev/db_auth.env
    command: --init-db --test
    volumes:
      - ./cover:/srv/mapstory/cover

  celery:
    links:
      - postgres
    extra_hosts:
      - docker:nginx
    env_file:
      - docker/env/dev/public_host.env
      - docker/env/dev/geoserver.env
      - docker/env/dev/mapstory.env
      - docker/env/dev/db_auth.env
    volumes:
      - mapstory_media:/var/lib/mapstory/media/
      - mapstory_static:/var/lib/mapstory/static/

  geoserver:
    links:
      - postgres
    extra_hosts:
      - docker:nginx
    env_file:
      - docker/env/dev/public_host.env
      - docker/env/dev/geoserver.env
      - docker/env/dev/db_auth.env
    volumes:
      - geoserver:/var/lib/geoserver

  nginx:
    env_file:
      - docker/env/dev/public_host.env
    extra_hosts:
      - docker:nginx

volumes:
  postgres:
