FROM mapstory/geoserver:latest
MAINTAINER Tyler Battle <tbattle@boundlessgeo.com>

ENV GS_LIB=$WEBAPPS_DIR/geoserver/WEB-INF/lib

RUN set -e \
    && wget -qO /tmp/geogig-plugin.zip https://github.com/locationtech/geogig/releases/download/v1.1.0/geoserver-2.9-SNAPSHOT-geogig-plugin.zip \
    && rm $GS_LIB/*geogig* \
    && rm $GS_LIB/compress-lzf* \
    && rm $GS_LIB/gson* \
    && rm $GS_LIB/rocksdb* \
    && unzip -o /tmp/geogig-plugin.zip -d $GS_LIB \
    && rm /tmp/geogig-plugin.zip
